### ISSUE TITLE
该项目现在还能使用吗？

### ISSUE THREAD

**Issue by wkzqn** [xcosmosbox/wechaty-PaimonBot#1]

**Comment by xcosmosbox** [comment]
已过时，该项目的重要依赖包 _WECHATY-PUPPET-WECHAT_ 前几个月有多次重要更新，其中一部分对象的函数被改变，整个项目有太多需要修改的地方（导入不同的包，修改登录函数，修改过时的语法等等）。但依赖包本身还在被维护，如果急于使用，可以前往：https://github.com/wechaty/puppet-wechat 自行实现所需的功能。（主要还是太懒了我，还没放假😂现在正在期末周）

**Comment by wkzqn** [comment]
谢谢。您的邮件已收到，我会尽快处理。

**Comment by wkzqn** [comment]
谢谢。您的邮件已收到，我会尽快处理。
